[project]
name = "bot-mysystemdown"
version = "0.1.0"
description = "This is a bot that check endpoints and send a message if they are down."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "celery>=5.6.2",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
]
